name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libhdf5-dev \
          libpq-dev \
          ninja-build \
          pkg-config \
          libgrpc++-dev \
          libgrpc-dev \
          protobuf-compiler-grpc \
          libarmadillo-dev \
          libmlpack-dev \
          libensmallen-dev \
          liblapack-dev \
          libblas-dev

    - name: Install CMake 3.27 and Ninja
      uses: lukka/get-cmake@latest

    - name: Configure with CMake
      run: cmake --preset CI

    - name: Build
      run: cmake --build build --config Release
    