name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo dnf -y update
        sudo dnf -y install \
          hdf5-devel \
          libpq-devel \
          grpc-devel \
          mlpack-devel

    - name: Install CMake 3.27 and Ninja
      uses: lukka/get-cmake@latest

    - name: Configure with CMake
      run: cmake --preset Release

    - name: Build
      run: cmake --build --preset Release
    
