name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libhdf5-dev \
          libpq-dev \
          libgrpc++-dev \
          libprotobuf-dev \
          libstb-dev \
          libmlpack-dev \
          libensmallen-dev \
          protobuf-compiler

    - name: Install CMake 3.27 and Ninja
      uses: lukka/get-cmake@latest

    - name: Configure with CMake
      run: cmake --preset Release

    - name: Build
      run: cmake --build build --preset Release
    
